import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://fav.farm/🔥" />
      </head>
      <body className={inter.className}>
        <div className="container space-y-4">
          <div>
            <h1 className="text-4xl font-bold my-10">Marketplace</h1>
          </div>
          <nav className="space-x-2 border border-solid [&>*]:p-4 [&>*]:inline-block rounded-lg">
            <Link href="/">Home</Link>
            <Link href="/listings">Listings</Link>
          </nav>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
